In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.13.0'

In [4]:
dataset = pd.read_csv('Power Plant.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [11]:
print(x)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


Splitting into train and test set

In [12]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


In [5]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

ANN

In [6]:
ann = tf.keras.models.Sequential()

Adding layers

In [7]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann.add(tf.keras.layers.Dense(units=1))

Training

In [8]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')


In [9]:
ann.fit(x_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
240/240 [==============================] - 2s 2ms/step - loss: 424338.8438
Epoch 2/100
240/240 [==============================] - 1s 2ms/step - loss: 125275.9375
Epoch 3/100
240/240 [==============================] - 1s 2ms/step - loss: 14304.0859
Epoch 4/100
240/240 [==============================] - 1s 2ms/step - loss: 267.8577
Epoch 5/100
240/240 [==============================] - 1s 2ms/step - loss: 242.3015
Epoch 6/100
240/240 [==============================] - 0s 2ms/step - loss: 240.0054
Epoch 7/100
240/240 [==============================] - 1s 2ms/step - loss: 237.4162
Epoch 8/100
240/240 [==============================] - 1s 2ms/step - loss: 234.6563
Epoch 9/100
240/240 [==============================] - 1s 2ms/step - loss: 231.4495
Epoch 10/100
240/240 [==============================] - 1s 2ms/step - loss: 228.3350
Epoch 11/100
240/240 [==============================] - 1s 2ms/step - loss: 224.4969
Epoch 12/100
240/240 [==============================] - 1s 2ms/ste

In [13]:
y_pred = ann.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

60/60 [==============================] - 0s 1ms/step
[[431.16 431.23]
 [462.3  460.01]
 [465.83 461.14]
 ...
 [473.03 473.26]
 [439.85 438.  ]
 [459.06 463.28]]
